#!/usr/bin/env python3
"""Rebuild the ~/ClaudeVault/CLAUDE.md index file.

Walks the vault tree, parses frontmatter from all notes, and generates a
comprehensive index with tag cloud, recent activity, and per-folder listings.
Uses only Python stdlib.
"""

import sys
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path

# These scripts are not a proper package — sys.path.insert is intentional so
# each script can run standalone via ``uv run`` or ``python`` without requiring
# pip install or editable installs.  See ARC-009 in AUDIT.md.
sys.path.insert(0, str(Path(__file__).parent))

from vault_common import (
    VAULT_ROOT,
    all_vault_notes,
    ensure_vault_dirs,
    get_body,
    git_commit_vault,
    parse_frontmatter,
)

# Canonical folder order for index sections
FOLDER_ORDER: list[str] = [
    "Daily",
    "Projects",
    "Languages",
    "Frameworks",
    "Patterns",
    "Debugging",
    "Tools",
    "Research",
    "History",
]

RECENT_DAYS: int = 7
RECENT_MAX: int = 20
SUMMARY_MAX_CHARS: int = 80


def _extract_title(content: str, filename_stem: str) -> str:
    """Extract the title from the first ``#`` heading in the body, falling back to filename."""
    body: str = get_body(content)
    for line in body.splitlines():
        stripped: str = line.strip()
        if stripped.startswith("#"):
            title: str = stripped.lstrip("#").strip()
            if title:
                return title
    return filename_stem


def _extract_summary(content: str) -> str:
    """Return the first non-empty, non-heading, non-comment body line, truncated to 80 chars."""
    body: str = get_body(content)
    for line in body.splitlines():
        stripped: str = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith("<!--"):
            continue
        if len(stripped) > SUMMARY_MAX_CHARS:
            return stripped[: SUMMARY_MAX_CHARS - 3] + "..."
        return stripped
    return ""


def _folder_name(note_path: Path) -> str:
    """Return the immediate parent folder name relative to VAULT_ROOT.

    For notes directly in VAULT_ROOT, returns an empty string.
    """
    try:
        rel: Path = note_path.relative_to(VAULT_ROOT)
    except ValueError:
        return ""
    parts: tuple[str, ...] = rel.parts
    if len(parts) <= 1:
        return ""
    return parts[0]


def _wikilink(note_path: Path) -> str:
    """Return a wikilink ``[[stem]]`` for the note."""
    return f"[[{note_path.stem}]]"


def build_index() -> tuple[str, int, int]:
    """Build the full CLAUDE.md index content.

    Returns:
        A tuple of (index_content, note_count, tag_count).
    """
    ensure_vault_dirs()
    notes: list[Path] = all_vault_notes()

    now_str: str = datetime.now().strftime("%Y-%m-%d %H:%M")
    cutoff_ts: float = (datetime.now() - timedelta(days=RECENT_DAYS)).timestamp()

    # Collected data per note
    tag_counter: Counter[str] = Counter()
    recent_notes: list[
        tuple[float, Path, str, str]
    ] = []  # (mtime, path, folder, summary)
    folder_notes: dict[
        str, list[tuple[str, str, str]]
    ] = {}  # folder -> [(wikilink, title, summary)]

    for note_path in notes:
        try:
            content: str = note_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue

        fm: dict[str, object] = parse_frontmatter(content)
        title: str = _extract_title(content, note_path.stem)
        summary: str = _extract_summary(content)
        folder: str = _folder_name(note_path)

        # Collect tags
        tags: object = fm.get("tags")
        if isinstance(tags, list):
            for tag in tags:
                if isinstance(tag, str) and tag:
                    tag_counter[tag] += 1

        # Check recency
        try:
            mtime: float = note_path.stat().st_mtime
        except OSError:
            mtime = 0.0

        if mtime >= cutoff_ts:
            recent_notes.append((mtime, note_path, folder, summary))

        # Group by folder
        if folder:
            folder_notes.setdefault(folder, []).append(
                (_wikilink(note_path), title, summary)
            )

    # Sort recent by mtime descending, limit
    recent_notes.sort(key=lambda x: x[0], reverse=True)
    recent_notes = recent_notes[:RECENT_MAX]

    # Sort notes within each folder alphabetically by wikilink
    for folder in folder_notes:
        folder_notes[folder].sort(key=lambda x: x[0].lower())

    total_notes: int = len(notes)
    total_tags: int = len(tag_counter)

    # --- Build output ---
    lines: list[str] = []
    lines.append("# Claude Vault Index")
    lines.append("")
    lines.append(f"> Auto-generated by update_index.py on {now_str}")
    lines.append("> Do not edit manually - changes will be overwritten")
    lines.append("")

    # Quick Stats
    lines.append("## Quick Stats")
    lines.append(f"- **Total notes**: {total_notes}")
    lines.append(f"- **Last updated**: {now_str}")
    lines.append("")

    # Conventions (always emitted so they survive index rebuilds)
    lines.append("## Conventions")
    lines.append("")
    lines.append(
        "- **Frontmatter required** on every note (date, type, tags, confidence, sources, related)."
    )
    lines.append(
        "- **Kebab-case filenames**, 3-5 words, no date suffix — date goes in frontmatter."
    )
    lines.append(
        "- **No orphan notes** — every note must link to at least one other note via `related`."
    )
    lines.append(
        "- **Search before create** — update existing notes rather than creating duplicates."
    )
    lines.append(
        "- **Subfolder rule** — when 3 or more notes share a common subject prefix, move them"
    )
    lines.append(
        "  into a named subfolder. Drop the redundant prefix from filenames inside the folder."
    )
    lines.append(
        "  Only one level of subfolder is allowed — never nest subfolders within subfolders."
    )
    lines.append(
        "  Example: `Research/fastapi-middleware-basics.md` + `fastapi-middleware-auth.md` + `fastapi-middleware-cors.md`"
    )
    lines.append("  → `Research/fastapi-middleware/basics.md`, `auth.md`, `cors.md`.")
    lines.append(
        "  Update all `[[wikilinks]]` and run `update_index.py` after reorganizing."
    )
    lines.append("")

    # Tag Cloud (human-readable, sorted by frequency)
    lines.append("## Tag Cloud")
    if tag_counter:
        tag_parts: list[str] = []
        for tag, count in tag_counter.most_common():
            tag_parts.append(f"`{tag}` ({count})")
        lines.append(" | ".join(tag_parts))
    else:
        lines.append("_No tags found._")
    lines.append("")

    # Existing Tags (machine-readable for the AI summarizer)
    lines.append("## Existing Tags")
    if tag_counter:
        lines.append(", ".join(sorted(tag_counter.keys())))
    else:
        lines.append("")
    lines.append("")

    # Recent Activity
    lines.append(f"## Recent Activity ({RECENT_DAYS} days)")
    if recent_notes:
        for _mtime, note_path, folder, summary in recent_notes:
            wlink: str = _wikilink(note_path)
            folder_label: str = f" ({folder})" if folder else ""
            summary_label: str = f" - {summary}" if summary else ""
            lines.append(f"- {wlink}{folder_label}{summary_label}")
    else:
        lines.append("_No recent activity._")
    lines.append("")

    # Folder sections
    lines.append("## Folders")
    lines.append("")

    for folder_name_str in FOLDER_ORDER:
        entries: list[tuple[str, str, str]] = folder_notes.get(folder_name_str, [])
        count: int = len(entries)
        lines.append(f"### {folder_name_str} ({count} notes)")
        if entries:
            for wlink, title, summary in entries:
                summary_label = f" - {summary}" if summary else ""
                lines.append(f"- {wlink}{summary_label}")
        else:
            lines.append(f"_No notes in {folder_name_str}._")
        lines.append("")

    # Handle any extra folders not in FOLDER_ORDER
    extra_folders: list[str] = sorted(f for f in folder_notes if f not in FOLDER_ORDER)
    for folder_name_str in extra_folders:
        entries = folder_notes[folder_name_str]
        count = len(entries)
        lines.append(f"### {folder_name_str} ({count} notes)")
        for wlink, title, summary in entries:
            summary_label = f" - {summary}" if summary else ""
            lines.append(f"- {wlink}{summary_label}")
        lines.append("")

    return "\n".join(lines), total_notes, total_tags


def main() -> None:
    """Entry point: rebuild the index and write it to CLAUDE.md."""
    content, note_count, tag_count = build_index()
    index_path: Path = VAULT_ROOT / "CLAUDE.md"
    index_path.write_text(content, encoding="utf-8")
    git_commit_vault("chore(vault): rebuild index")
    print(f"Updated CLAUDE.md: {note_count} notes indexed, {tag_count} tags")


if __name__ == "__main__":
    main()
